# TEST
version: '2'
services:
  myappdb:
    build: mysql
    volumes:
      - laraveldb:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
  
  web:
    build: web
    #command: /etc/init.d/apache2 restart
    volumes:
      - ./projects:/var/www/html/
      - ./web/conf:/etc/apache2/sites-enabled
    ports:
      - "3000:80"
    depends_on:
      - myappdb
volumes:
  laraveldb:
